apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-database-claim
spec:
  storageClassName: local-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
