apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - image: frontend:latest
      name: frontend
      imagePullPolicy: Never
      ports:
        - containerPort: 80
