apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  containers:
    - image: keycloak:4.6.0.Final
      name: keycloak
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: KEYCLOAK_USER
          value: "administrator"
        - name: KEYCLOAK_PASSWORD
          value: "administrator"
