apiVersion: v1
kind: Service
metadata:
  name: server-lb
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: server
