apiVersion: v1
kind: Pod
metadata:
  name: tomcat-server
  labels:
    app: server
spec:
  containers:
    - image: tomcat-server:latest
      name: tomcat-server
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
