apiVersion: v1
kind: Service
metadata:
  name: database-lb
spec:
  ports:
    - name: "1521"
      port: 1521
      protocol: TCP
      targetPort: 1521
    - name: "5500"
      port: 5500
      protocol: TCP
      targetPort: 5500
  type: LoadBalancer
  selector:
    app: db
